### ISSUE TITLE
v1 Roadmap

### ISSUE THREAD

**Issue by bloha** [rajce-client/kernel#1]
# v1 Roadmap
- [ ] Schedule tasks with the priority queue
- [ ] Add the ability to manage the number of running tasks
- [ ] Add the ability to abort a task
- [ ] Add the ability to pause a task
- [ ] Add the ability to resume a paused task
- [ ] Use exponential backoff for tasks
- [ ] Set a timeout for a task
- [ ] Run more tasks if running tasks do not respond
